# NumPy

In [1]:
import numpy as np 


## Numpy Arrays 

In [3]:
my_list = [1,2,3]

In [4]:
x = np.array(my_list) # to use numpy we call np and then .
# the array funcion needs to be passed an object such as a list 

In [5]:
type(x)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix) # np knows this is a 2 dimensional matrix since it is lists separated by commas 
# notice the number of brackets in the begining and end - there are two brackets indicating a two dimentional array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# built in methods for arrays 
list(range(0,5))

[0, 1, 2, 3, 4]

In [9]:
np.arange(0,5) # same as list from above just np's version 

array([0, 1, 2, 3, 4])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(3) # just creates an array of 0s 

array([0., 0., 0.])

In [12]:
type(1)

int

In [13]:
type(1.9)

float

In [14]:
np.zeros((5,5)) # 2 dimension array with zeros 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.linspace(0,10,10) # linearly spaced elements takes in start stop and how many in between 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [20]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
# np's random library

np.random.rand(1) # random number between 0 and 1 

array([0.87982365])

In [22]:
np.random.rand(5,4) # 5 by 4 matrix of random numbers between 0 and 1 with unifirom distribution meaning all the numbers have the same odds to be selected 

array([[0.43580945, 0.01368215, 0.32708003, 0.62713619],
       [0.78613886, 0.06534141, 0.04008688, 0.82262807],
       [0.20453362, 0.75392375, 0.55225948, 0.38004713],
       [0.28853894, 0.38897676, 0.12560309, 0.77029641],
       [0.36523528, 0.60700433, 0.09363755, 0.50404857]])

In [23]:
np.random.randn(5,4)  # randn = normal dist as opposed to uniform dist - just means the closer you are to 0 standard deviation the higher prob you have to be picked (think normal dist curve)

array([[ 0.33827729,  0.53798121,  0.00947442, -1.39180978],
       [-0.22280496,  1.49889673, -0.35584044,  0.24493003],
       [-0.09460914, -0.35811127, -0.0654208 ,  2.07698955],
       [ 0.5537353 , -1.15379652, -1.1925971 , -0.42276643],
       [ 1.32487514, -1.44553236,  0.16839147,  0.44777271]])

In [26]:
np.random.randint(1,100) # random number from 1 up to not including 100

96

In [27]:
np.random.randint(1,100, 10) # the added 10 here tells it to give 10 random ints between 1 and 100 

array([13,  3, 58, 21, 77, 36, 29, 71, 86, 74])

In [29]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [30]:
# can reshape from default shape to a different array shape 
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
# reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# shape
arr.shape

(25,)

In [33]:
# .max()
# .argmax - gives the index location of the max in the array 
# .min()
ranarr.max()
ranarr.argmax()

46

## Numpy Operations

In [2]:
import numpy as np  
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + arr # adds it by an element by element addition

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [4]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr/arr # if you have a zero in an array it gives you a warning and puts a nan in the place of the zero. Same with infinity 

c:\Users\LW6412\Anaconda3\envs\dev\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [7]:
np.sqrt(arr) # take square root of everything in the array 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [8]:
# find the max of the array 
np.max(arr)

9

In [9]:
# there are tons of mathematical opporators for arrays in the np module 
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## NumPy Indexing 

In [ ]:
import numpy as np

In [10]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[8] # returns the 8th element in the array 

8

In [ ]:
arr[1:5] # returns everything up to not including 5th element 

In [ ]:
arr[3:] # starting at 3rd element up to last 

In [12]:
# broadcasting is basically replacing elements of an array with another element 
arr[0:5] = 100
arr 

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
sliceOfArray = arr[0:6]
sliceOfArray

array([0, 1, 2, 3, 4, 5])

In [17]:
sliceOfArray[:] = 99 # change all elements to 99
sliceOfArray

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arrCopy = arr.copy() # can create copy of array with .copy
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
mat = np.array([[5,10,15], [20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
mat[0] # grab all three numbers from the first element which is an array nested in an array 

array([ 5, 10, 15])

In [24]:
# to grab an individual element 
mat[1][1] # index 1 row in the index 1 column 

25

In [25]:
# can also use comma notation instead of brackets
mat[1,1]

25

In [26]:
# select 40
mat[2,1]

40

In [27]:
# 2d array slicing 
mat[:2,1:] # want everything from first row up to not including 2. Want columns starting at 1 and go to end. 

# syntax name of array[starting row index : ending row index, starting column index, ending column index]

array([[10, 15],
       [25, 30]])

In [28]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
# index out 20,25 and 35,40
mat[1:,0:2]

array([[20, 25],
       [35, 40]])

### CONDITIONAL SELECTION

In [30]:
arr = np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
# grab every element greater than 4 
arr > 4 

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
bool_arr = arr > 4

In [33]:
arr[bool_arr] # only returns array where the bool values are True 

array([ 5,  6,  7,  8,  9, 10])

In [3]:
test = [1,2,3,4]
test

[1, 2, 3, 4]